name: Lint YAML
on:
  pull_request:
    branches: ['main']

# Enforce least privilege permissions to secure the workflow against token misuse
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run yamllint
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
          yamllint action.yaml
