name: Security Actions

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

  # Scan on-demand through GitHub Actions interface
  workflow_dispatch: {}

  # Scan mainline branches when there is change in security.yml file:
  push: {}

  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '33 5 * * 1'
    # It is recommended to change the schedule to a random time.

# Enforce least privilege permissions to secure the workflow against token misuse
permissions:
  contents: read

jobs:
  # Calling Security Reusable action which would in turn call other reusable actions example - Semgrep
  call_security:
    uses: falconxio/security-actions/.github/workflows/security.yml@master
    secrets: inherit
